#!/usr/bin/env node
/**
 * Export the floci (local AWS emulator) connection settings into `.env.local`
 * so SvelteKit dev server, vitest and the seed scripts all talk to floci.
 *
 * Usage:
 *   node scripts/floci-env.ts            # write .env.local
 *   node scripts/floci-env.ts --print    # print `export KEY=value` lines
 *   node scripts/floci-env.ts --check    # verify the endpoint answers
 *   node scripts/floci-env.ts --remove   # delete .env.local (go back to real AWS)
 */
import { execFileSync } from 'node:child_process';
import { existsSync, rmSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const rootDir = dirname(dirname(fileURLToPath(import.meta.url)));
const envFile = join(rootDir, '.env.local');

const args = new Set(process.argv.slice(2));

type EnvRecord = Record<string, string>;

/** Parse the `export KEY='value'` lines printed by `floci env`. */
export function parseFlociEnv(output: string): EnvRecord {
	const result: EnvRecord = {};
	for (const line of output.split('\n')) {
		const match = /^\s*export\s+([A-Z0-9_]+)=(.*)$/.exec(line);
		if (!match) continue;
		const raw = match[2].trim();
		const value = raw.replace(/^(['"])(.*)\1$/, '$2');
		result[match[1]] = value;
	}
	return result;
}

/** `floci env` output for the running AWS emulator, or throw with a clear message. */
export function readFlociEnv(): EnvRecord {
	try {
		const output = execFileSync('floci', ['env'], {
			encoding: 'utf8',
			stdio: ['ignore', 'pipe', 'pipe'],
		});
		return parseFlociEnv(output);
	} catch (error) {
		const detail = error instanceof Error ? error.message : String(error);
		throw new Error(
			`Could not read the floci environment. Is the CLI installed and the emulator started?\n` +
				`  install: curl -fsSL https://floci.io/install.sh | sh\n` +
				`  start:   pnpm floci:start\n` +
				`underlying error: ${detail}`,
			{ cause: error },
		);
	}
}

/** Build the dotenv contents for a floci configuration. */
export function toEnvFile(values: EnvRecord): string {
	const lines = [
		'# Generated by `pnpm floci:env`. Local AWS emulator settings, safe to delete.',
		`AWS_ENDPOINT_URL=${values.AWS_ENDPOINT_URL}`,
		`AWS_DEFAULT_REGION=${values.AWS_DEFAULT_REGION ?? 'us-east-1'}`,
		`AWS_REGION=${values.AWS_DEFAULT_REGION ?? 'us-east-1'}`,
		`AWS_ACCESS_KEY_ID=${values.AWS_ACCESS_KEY_ID ?? 'test'}`,
		`AWS_SECRET_ACCESS_KEY=${values.AWS_SECRET_ACCESS_KEY ?? 'test'}`,
		'',
	];
	return lines.join('\n');
}

async function checkEndpoint(endpoint: string): Promise<boolean> {
	try {
		const response = await fetch(endpoint, { signal: AbortSignal.timeout(3000) });
		return response.status < 500;
	} catch {
		return false;
	}
}

async function main(): Promise<void> {
	if (args.has('--remove')) {
		if (existsSync(envFile)) {
			rmSync(envFile);
			console.log(`Removed ${envFile}`);
		} else {
			console.log(`${envFile} does not exist, nothing to remove`);
		}
		console.log('The app will now use ambient AWS credentials against the real AWS endpoints.');
		return;
	}

	const values = readFlociEnv();
	const endpoint = values.AWS_ENDPOINT_URL;

	if (args.has('--print')) {
		for (const [key, value] of Object.entries(values)) {
			console.log(`export ${key}='${value}'`);
		}
		return;
	}

	if (args.has('--check')) {
		const reachable = await checkEndpoint(endpoint);
		console.log(`floci endpoint ${endpoint}: ${reachable ? 'reachable' : 'NOT reachable'}`);
		console.log(`.env.local present: ${existsSync(envFile) ? 'yes' : 'no'}`);
		process.exitCode = reachable ? 0 : 1;
		return;
	}

	writeFileSync(envFile, toEnvFile(values), 'utf8');
	console.log(`Wrote ${envFile}`);
	console.log(`  AWS_ENDPOINT_URL=${endpoint}`);
	console.log(`  AWS_DEFAULT_REGION=${values.AWS_DEFAULT_REGION ?? 'us-east-1'}`);
	console.log('  WATCH_TAIL_REGIONS=<unset: the picker offers every CloudWatch Logs region>');
	console.log('\nNext: pnpm seed   (create sample log groups and events)');
}

const invokedDirectly = process.argv[1] && process.argv[1].endsWith('floci-env.ts');
if (invokedDirectly) {
	await main();
}
